### ISSUE TITLE
Add all pages

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/amazon-marketplace-react#1]
### Tasks

- [ ] Add Home Page
- [ ] Add Wishlist Page
- [ ] Add Checkout Page
- [ ] Add NavigationBar on each page
- [ ] Should be able to route via NavigationBar

![image](https://user-images.githubusercontent.com/10376859/214649075-a696f753-f74f-40a1-b6d4-a1b3dc70dd2e.png)
